extern const char *circlemud_version;
extern const char *dirs[];
extern const char *room_bits[];
extern const char *exit_bits[];
extern const char *sector_types[][11];
extern const char *genders[];
extern const char *position_types[];
extern const char *player_bits[];
extern const char *action_bits[];
extern const char *preference_bits[];
extern const char *extended_bits[];
extern const char *affected_bits[];
extern const char *timer_types[];
extern const char *battery_types[];
extern const char *connected_types[];
extern const int  wear_positions[];
extern const char *punish_types[]; // ARTUS
extern const char *offence_types[]; // ARTUS
extern const char *where[];
extern const char *equipment_types[];
extern const char *item_types[];
extern const char *wear_bits[];
extern const char *extra_bits[];
extern const char *apply_types[];
extern const char *container_bits[];
extern const char *drinks[];
extern const char *drinknames[];
extern const char *color_liquid[];
extern const char *fullness[];
extern const char *spell_wear_off_msg[];
extern const char *pc_class_types[];
extern const char *pc_race_types[];
extern const char *npc_class_types[];
extern const char *weekdays[];
extern const char *month_name[];
extern const char *moon_mesg[];
extern const char *sort_names[];
extern const char *world_names[]; 
extern const char *zone_flagbits[];
extern const char *stat_names[];

extern const struct str_app_type str_app[];
extern const struct dex_skill_type dex_app_skill[];
extern const struct dex_app_type dex_app[];
extern const struct con_app_type con_app[];
extern const struct int_app_type int_app[];
extern const struct wis_app_type wis_app[];
extern const float class_modifiers[];
extern const float race_modifiers[];
extern const int default_item_damage[];
extern int rev_dir[];
extern int movement_loss[];
extern int drink_aff[][3];
extern const int default_colour_codes[];
extern const int thaco_ac[LVL_CHAMP][NUM_CLASSES];
extern char *colour_headings[];
extern const long pc_race_eq_masks[];
extern const int pc_class_primary_stats[];
extern const int pc_max_race_stats[][6];
extern const int pc_max_class_points[][3];
extern const int stat_costs[];
extern const float stat_mods[];
extern const char *burgle_rooms[];
extern const char *mobprog_types[];
extern const char *race_abbrevs[];
extern const char *class_abbrevs[];
extern const char *cmd_types[];
extern const char *cmd_bhelp[];
